### ISSUE TITLE
Check For Unassigns; Disable Self Assigns

### ISSUE THREAD

**Issue by 0x4007** [ubiquibot/command-start-stop#2]
> Before disqualification, the manager should ask for an update. If the contributor still has no updates, then the manager should disqualify the contributor by unassigning them, and ideally, not allowing them to reassign themselves (we could check in the `/start` command if the contributor was ever unassigned within the issue timeline.)

_Originally posted by @0x4007 in https://github.com/ubiquibot/plugins-wishlist/issues/7#issuecomment-2146804481_

**Comment by gentlementlegen** [comment]
@0x4007 Seems there has been some issues since we updated the Bot. Here is the link to the error for reference:
https://supabase.com/dashboard/project/wfzpewmlyiozupulbuur/editor/28943?sort=created%3Adesc&filter=level%3Aneq%3Ainfo&filter=id%3Aeq%3A983125

**Comment by gitcoindev** [comment]
From the logs I see it failed on creating a label when it already existed:

``` "response": {
      "url": "https://api.github.com/repos/ubiquibot/command-start-stop/labels",
      "data": {
        "errors": [
          {
            "code": "already_exists",
            "field": "name",
            "resource": "Label"
          }
        ],
        "message": "Validation Failed",
        "documentation_url": "https://docs.github.com/rest/issues/labels#create-a-label"
      },
      "status": 422,
```

**Comment by Keyrxng** [comment]
@jordan-ae we are in a mission critical stage right now and these tasks you are working have a sense of urgency behind them and we need to be pushing things forward.

With this in mind, I am going to keep you assigned and I will assign myself too like a little dream team. I'll push things forward with this task while you work on the tests for the other one, this way we have progress and in the end you will still be rewarded for this task

**Comment by jordan-ae** [comment]
> @jordan-ae we are in a mission critical stage right now and these tasks you are working have a sense of urgency behind them and we need to be pushing things forward.
> 
> With this in mind, I am going to keep you assigned and I will assign myself too like a little dream team. I'll push things forward with this task while you work on the tests for the other one, this way we have progress and in the end you will still be rewarded for this task

Got you sorry for the delay!

**Comment by Keyrxng** [comment]
@jordan-ae considering https://github.com/ubiquity/devpool-directory-bounties/issues/31, technically you should have resolved the issue in order to not receive a debit against future rewards but it was urgent and completed by someone else which is not your fault.

However it does mean you received a reward for a task which you did not complete and this task here was dual-assigned as a goodwill gesture. For this reason it make sense to allow you to keep the reward from https://github.com/ubiquity/devpool-directory-bounties/issues/31 ($150) and not receive assignee rewards from this task ($100)

**Comment by jordan-ae** [comment]
You are right @Keyrxng I took the weekend off for health reasons didn't see the bug in the script play out. I would have really loved to clean it up unfortunately I saw the thread on sunday night when it was already too late.

**Comment by Keyrxng** [comment]
> You are right @Keyrxng I took the weekend off for health reasons didn't see the bug in the script play out.

I hope you are well dude sorry to hear that.

> I would have really loved to clean it up unfortunately I saw the thread on sunday night when it was already too late.

Ah dw there are plenty more tasks in the sea so-to-speak

**Comment by 0x4007** [comment]
@gentlementlegen my permit didn't work for this one, perhaps you can let me know where I can find it.

**Comment by gentlementlegen** [comment]
@0x4007 I generated then deleted so users cannot claim twice. You can re-generate for yourself I guess.
