### ISSUE TITLE
New text config param for empty wallet

### ISSUE THREAD

**Issue by rndquu** [ubiquibot/command-start-stop#22]
Depends on https://github.com/ubiquity/safe.ubq.fi/issues/3

We're going to have 2 registration flows:
1. Our usual flow via the `/wallet` command
2. A new one via webauthn and `safe.ubq.fi` ([example](https://github.com/ubiquibot/plugins-wishlist/issues/35#issue-2465056368))

The `command-start-stop` plugin displays a warning message when `startRequiresWallet = true` and user doesn't have a registered wallet:
```
Please set your wallet address with the /wallet command first and try again.
``` 

Since we're going to have 2 flows the message above is not applicable for the "webauthn" flow. Possible solution could be to add a new plugin option for the warning message like `emptyWalletText`.

**Comment by gentlementlegen** [comment]
@whck6 you should first `/start` to assign yourself to this issue and notify users that you are working on it.

**Comment by whck6** [comment]
@Keyrxng,  May I know when I will receive 25 WXDAI? I feel It would be immediate but no.

**Comment by Keyrxng** [comment]
@whck6 is the permit above not working?

We are aware of a slight issue with permit generation at the moment which is being resolved as we speak. If we need to we will regenerate the permit if you haven't claimed it by then by it should be resolved within 24 hrs
