### ISSUE TITLE
Assign user on PR opening

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/command-start-stop#26]
I believe that the v1 of the bot would automatically assign a user to an issue if that said user would open a pull-request against an issue. Currently this doesn't happen, for example in https://github.com/ubiquibot/command-start-stop/issues/22

I do not know how this would play with the maximum assigned issues however, if a user would be above the maximum allowed threshold.

**Comment by 0x4007** [comment]
It respects that rule. If they hit their limit it simply doesn't assign them

**Comment by gentlementlegen** [comment]
I will read the old bot code more in detail, but for now the question I had would be:
- if there is already a user assigned, and another user opens a PR against an issue, does it close the PR saying this is already assigned or shall we assign 2 users to the issue (I guess not since it can be abused)?

**Comment by 0x4007** [comment]
It just follows the start logic. Basically it doesn't do anything in that scenario.

**Comment by 0x4007** [comment]
No idea why I set this to one week.
