### ISSUE TITLE
Text formatting issue on `/stop` if the user is not assigned

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/command-start-stop#32]
There seem to be an issue with the displayed text in this scenario:
https://github.com/ubiquibot/sandbox/issues/21#issuecomment-2315946988

The output should be
```diff
! You are not assigned to this task
 ```

**Comment by 0x4007** [comment]
> ```diff
> ! No wallet address found
> ```
> 

@gentlementlegen I think Star runs twice

**Comment by gentlementlegen** [comment]
@0x4007 I think both errors got triggered in the same run which caused 2 messages to be posted. I checked the configuration and the plugin is only there once, so I believe it is more of a code logic issue.

**Comment by 0x4007** [comment]
I think output from each plugin should be standardized with reward amount, message, and message level. 

Message referring to a single string to comment.
