### ISSUE TITLE
New Assign Message Design

### ISSUE THREAD

**Issue by 0x4007** [ubiquibot/command-start-stop#47]
# New design

<samp>
<table>
<tr><td>Deadline</td><td><b>Sat, Sep 14, 11:37 AM UTC</b></td></tr>
<tr><td>Beneficiary</td><td><b>0x4007CE2083c7F3E18097aeB3A39bb8eC149a341d</b></td></tr>
</table>
</samp>

> [!TIP]
> <ul> <li>Use <code>/wallet 0x0000...0000</code> if you want to update your registered payment wallet address.</li> <li>Be sure to open a draft pull request as soon as possible to communicate updates on your progress.</li> <li>Be sure to provide timely updates to us when requested, or you will be automatically unassigned from the task.</li> <ul>

_Originally posted by @ubiquity-os[bot] in https://github.com/ubiquibot/assistive-pricing/issues/33#issuecomment-2350931464_

**Comment by 0x4007** [comment]
Turns out that the code was broken when I worked on this so my changes can be rebased on head for a fix. 

I'm at a conference so I can't this week.

**Comment by gentlementlegen** [comment]
@0x4007 Do you want me to rebase your PR and reopen it, or it is not an emergency and you'll do that next week?

**Comment by 0x4007** [comment]
You can rebase probably and no it's not an emergency but should only take a few seconds

**Comment by gentlementlegen** [comment]
@0x4007 Tested it on my org as is, seems there are some display issues, will fix and open the PR for review: https://github.com/Meniole/command-start-stop/issues/22
