### ISSUE TITLE
Fix default schema values

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/command-start-stop#51]
It appears to me that the logic to decode the schema is wrong, and this would be introduced by Jordan's PR addition regarding the configuration accepting the amount of parallel tasks allowed for each user. If not provided, the default configuration fails which is why it is failing in your last try, on ubiquity / ubiquibot orgs, but not on mine where I provide the full config. Working on a fix right now.

_Originally posted by @gentlementlegen in https://github.com/ubiquibot/permit-generation/issues/60#issuecomment-2351912070_
            

The default values when not provided via the config are:
```
{ admin: Infinity, member: 10, contributor: 2 }
```
`Infinity` does not satisfy `T.Record(T.String(), T.Integer())` since it is not an integer value.

Tasks to be carried out:
- properly log the errors so it is easier to identify
- add a test related to the default configuration if none
- fix the default values

**Comment by 0x4007** [comment]
I'm surprised that jest test didn't catch this. I guess there isn't one to check defaults.
