### ISSUE TITLE
Max Tasks

### ISSUE THREAD

**Issue by 0x4007** [ubiquibot/command-start-stop#8]
The old version has the ability to set limits. 

Based on the contributor level (collaborator, admin etc) we should be able to configure limits. 

Block start if they are assigned to more than X tasks. 

This is useful for new people who self assign a ton of tasks and of course can't handle all of them so just blocks progress.

**Comment by Keyrxng** [comment]
@0x4007

> Based on the contributor level (collaborator, admin etc) we should be able to configure limits.

Do you have default values in mind off the top of your head? 

E.g: 

`admin === no limit`
`member === 10`
`contributor === 2`

**Comment by 0x4007** [comment]
> `admin === no limit` 
> `member === 5` 
> `contributor === 2`

Not sure about member, I guess will just set to 5

**Comment by 0x4007** [comment]
@Keyrxng @gentlementlegen  isn't this implemented already? I saw The error yesterday when testing team assigns.

**Comment by Keyrxng** [comment]
@0x4007 Was just about to start reviews, I think it should be ready now

**Comment by 0x4007** [comment]
Why are we rebuilding the feature if its already built and apparently working

**Comment by 0x4007** [comment]
Bad example but I can't find the example from my phone now

**Comment by Keyrxng** [comment]
I'm not sure what feature it is your a talking about. This issue focuses on improving the max assignable tasks based on the user's org role. `teams` is working and not being worked on, once this task is closed as complete task limits will be more dynamic than the flat rate of 3(i think) it is right now

**Comment by jordan-ae** [comment]
@0x4007 permits didn't generate

**Comment by gentlementlegen** [comment]
I updated the configuration accordingly. Also, it seems that the generation ran into an issue: the content is too long to evaluate, see [this run](https://github.com/ubiquibot/conversation-rewards/actions/runs/10828487091/job/30043960563#step:7:194).

**Comment by gentlementlegen** [comment]
@0x4007 It seems that the optimization wasn't enough, I'll investigate more and see exactly what the payload is and why is it so long beyond the large amount of comments.

**Comment by 0x4007** [comment]
I think check the length of the to-be-posted comment and if it exceeds the limit, you should only post the essentials (the permit link) along with a warning that explains its a truncated output

```diff
! This is a truncated output due to the comment length limits. 
```

**Comment by gentlementlegen** [comment]
@0x4007 In this specific case the length of the comment is around 84 000 characters. Should we just strip the metadata in such case an only leave the URL to the job run? The job run itself contains everything that is inside the metadata, so we wouldn't lose any info.

**Comment by 0x4007** [comment]
Sounds good enough for now.

**Comment by gentlementlegen** [comment]
On it, will open a PR soon.

**Comment by jordan-ae** [comment]
Got no comment incentives crazy😂🥲

**Comment by gentlementlegen** [comment]
@jordan-ae This was not intended to be claimable, I am not sure if I used a fake account or not. I will regenerate from the main branch once the fix is merged.

**Comment by jordan-ae** [comment]
> Pretty sure that's intended, the PR author doesn't get rewarded for their own comments on their own PR otherwise a contributor could game the system easily. The PR author is rewarded for comments on the issue separate from the PR comments.

If this is the case, the goal of preventing contributors from gaming the system makes sense. However, completely turning off PR incentives for authors seems a bit extreme. While comment incentives are designed to encourage reviewers to conduct thorough reviews, removing incentives for the PR author could reduce their enthusiasm to engage in the review process as well.

Rather than entirely removing comment rewards for PR authors, I believe it would make more sense to reduce the multiplier for their comments. This way, authors are still encouraged to participate in the discussion and provide valuable feedback without risking system abuse.

**Comment by 0x4007** [comment]
> PR author could reduce their enthusiasm to engage in the review process as well.

If they don't deliver on the task then they don't receive the task price reward. 

> I believe it would make more sense to reduce the multiplier for their comments. 

We want to disincentivize long reviews. We prefer contributors who ship high quality code, while achieving the full specification with minimal review time.

**Comment by jordan-ae** [comment]
@gentlementlegen are the claimable? Or it's just to test

**Comment by 0x4007** [comment]
They are claimable but coincidently I need to top up the wallet will do so asap

**Comment by jordan-ae** [comment]
@0x4007 okay ✅

**Comment by jordan-ae** [comment]
> They are claimable but coincidently I need to top up the wallet will do so asap 

@0x4007 still waiting 🙏

**Comment by 0x4007** [comment]
I set up a new wallet and moved all the funds so I decided to regenerate using the latest wallet.

**Comment by Keyrxng** [comment]
> I set up a new wallet and moved all the funds so I decided to regenerate using the latest wallet. I suppose if you already claimed from the first, then you should obviously not claim from the second!

Pretty sure I didn't claim from the first, can't find a claim for 179 so safe to assume I didn't
